### ISSUE TITLE
Cancel NNTP

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/phpNemoServer#1]
Les articles d'annulation du bleachbot ne sont pas pris en compte.
Voir la discussion ici :

http://news.nemoweb.net/?Jid=017b8b9e8142b4e95cb146d8c4161afa8f1f09b2@news.nemoweb.net

**Comment by yamo-nntp** [comment]
Est-ce que les dernières annulations sont passées?

**Comment by DuzzAtNemo** [comment]
J'ai vérifié dans fr.sci.chimie et les spams y sont toujours sur 'devnews'.

**Comment by yamo-nntp** [comment]
Apparemment ça fonctionne : http://devnews.nemoweb.net/?DataID=mvqdne9Cva7NN6fLnZ2dnUU7982dnZ2d@giganews.com

**Comment by yamo-nntp** [comment]
corrigé, dans ce domaine, il reste à corriger les superseedes
